image: docker:stable
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info
- apk add make

stages:
- build

build_image:
  stage: build
  script:
  - make docker
